### PR TITLE
List of projects

### PR DESCRIPTION
**Pull request by zagganoth**
Added list of projects

### CODE REVIEW

**Review by mpaqman — CHANGES_REQUESTED** [review]
Really good overall!

One small change that in my experience is import is to have lowercase directory names. Please make the "Projects" directory into "projects"

**Review by mpaqman — APPROVED** [review]

**Comment by mpaqman** [comment]
Closes #5 . Awesome work Anish! Thank you 😄

**Comment by jayden-chan** [comment]
Lmao might want to merge before closing :smile:

**Comment by mpaqman** [comment]
Hmm let me try that again. This PR closes #5

**Comment by mpaqman** [comment]
Yuuuuppppp lessons learned (for the whole world to see)

**Pull request merged**
